packages:
  - 'lifi'
  - 'layerzero-multichain-arbitrage'
  - 'v2-pool-monitor'
  - 'web'

catalog:
  vite: ^8.2.0
  vite-plus: 0.2.6

allowBuilds:
  better-sqlite3: true
  esbuild: true
  unrs-resolver: false
